// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetShopProject.Data;

#nullable disable

namespace PetShopProject.Migrations
{
    [DbContext(typeof(KingdomDBContext))]
    [Migration("20230212133402_testImgComm")]
    partial class testImgComm
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PetShopProject.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnimalId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnimalId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 17,
                            CategoryId = 3,
                            Description = "The orca or killer whale is a toothed whale belonging to the oceanic dolphin family, of which it is the largest member. It is the only extant species in the genus Orcinus and is recognizable by its black-and-white patterned body",
                            ImageName = "Images\\Orca.jpg",
                            Name = "Orca"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 6,
                            CategoryId = 2,
                            Description = "The Komodo dragon, also known as the Komodo monitor, is a member of the monitor lizard family Varanidae that is endemic to the Indonesian islands of Komodo, Rinca, Flores, and Gili Motang. It is the largest extant species of lizard, growing to a maximum length of 3 metres, and weighing up to 70 kilograms",
                            ImageName = "Images\\KomodoDragon.jpg",
                            Name = "Komodo Dragon"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 11,
                            CategoryId = 3,
                            Description = "Zebras are African equines with distinctive black-and-white striped coats. There are three living species: the Grévy's zebra, plains zebra, and the mountain zebra. Zebras share the genus Equus with horses and asses, the three groups being the only living members of the family Equidae",
                            ImageName = "Images\\Zebra.jpg",
                            Name = "Zebra"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 13,
                            CategoryId = 1,
                            Description = "The great white shark, also known as the white shark, white pointer, or simply great white, is a species of large mackerel shark which can be found in the coastal surface waters of all the major oceans",
                            ImageName = "Images\\Shark.jpg",
                            Name = "Great White Shark"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 2,
                            CategoryId = 4,
                            Description = "Toucans are members of the Neotropical near passerine bird family Ramphastidae. The Ramphastidae are most closely related to the American barbets. They are brightly marked and have large, often colorful bills. The family includes five genera and over forty different species",
                            ImageName = "Images\\Toucan.jpg",
                            Name = "Toucan"
                        },
                        new
                        {
                            AnimalId = 6,
                            Age = 2,
                            CategoryId = 5,
                            Description = "Poison dart frog is the common name of a group of frogs in the family Dendrobatidae which are native to tropical Central and South America. These species are diurnal and often have brightly colored bodies. This bright coloration is correlated with the toxicity of the species, making them aposematic",
                            ImageName = "Images\\Poison-Dart.jpg",
                            Name = "Poison Dart Frog"
                        },
                        new
                        {
                            AnimalId = 7,
                            Age = 4,
                            CategoryId = 2,
                            Description = "The king cobra is a venomous elapid snake species, endemic to South and Southeast Asia. It is sole member of the genus Ophiophagus. With an average length of 3.18 to 4 m, it is the world's longest venomous snake and possesses a potent neurotoxic venom that can cause the victim's death in 30 minutes",
                            ImageName = "Images\\Cobra.jpg",
                            Name = "Cobra Snake"
                        },
                        new
                        {
                            AnimalId = 8,
                            Age = 9,
                            CategoryId = 3,
                            Description = "The lion is a large cat of the genus Panthera native to Africa and India. It has a muscular, broad-chested body; short, rounded head; round ears; and a hairy tuft at the end of its tail. It is sexually dimorphic; adult male lions are larger than females and have a prominent mane",
                            ImageName = "Images\\Lion.jpg",
                            Name = "Lion"
                        },
                        new
                        {
                            AnimalId = 9,
                            Age = 7,
                            CategoryId = 3,
                            Description = "Kangaroos are four marsupials from the family Macropodidae (macropods, meaning \"large foot\"). In common use the term is used to describe the largest species from this family, the red kangaroo, as well as the antilopine kangaroo, eastern grey kangaroo, and western grey kangaroo",
                            ImageName = "Images\\Kangaroo.jpg",
                            Name = "Kangaroo"
                        },
                        new
                        {
                            AnimalId = 10,
                            Age = 1,
                            CategoryId = 1,
                            Description = "Pterois is a genus of venomous marine fish, commonly known as lionfish, native to the Indo-Pacific. It is characterized by conspicuous warning coloration with red or black bands, and ostentatious fins with venomous spines",
                            ImageName = "Images\\Lion-Fish.jpg",
                            Name = "LionFish"
                        },
                        new
                        {
                            AnimalId = 11,
                            Age = 2,
                            CategoryId = 4,
                            Description = "Swans are birds of the family Anatidae within the genus Cygnus. The swans' closest relatives include the geese and ducks. Swans are grouped with the closely related geese in the subfamily Anserinae where they form the tribe Cygnini. Sometimes, they are considered a distinct subfamily, Cygninae",
                            ImageName = "Images\\Swan.jpg",
                            Name = "Swan"
                        },
                        new
                        {
                            AnimalId = 12,
                            Age = 24,
                            CategoryId = 2,
                            Description = "The American alligator, sometimes referred to colloquially as a gator or common alligator, is a large crocodilian reptile native to the Southeastern United States. It is one of the two extant species in the genus Alligator, and is larger than the only other living alligator species, the Chinese alligator.",
                            ImageName = "Images\\American-Alligator.jpg",
                            Name = "American Alligator"
                        },
                        new
                        {
                            AnimalId = 13,
                            Age = 2,
                            CategoryId = 5,
                            Description = "The fire salamander is a common species of salamander found in Europe. It is black with yellow spots or stripes to a varying degree; some specimens can be nearly completely black while on others the yellow is dominant",
                            ImageName = "Images\\Fire-Salamder.jpg",
                            Name = "Fire Salamander"
                        },
                        new
                        {
                            AnimalId = 14,
                            Age = 5,
                            CategoryId = 1,
                            Description = "The mahi-mahi or common dolphinfish is a surface-dwelling ray-finned fish found in off-shore temperate, tropical, and subtropical waters worldwide. Also widely called dorado and dolphin, it is one of two members of the family Coryphaenidae, the other being the pompano dolphinfish",
                            ImageName = "Images\\mahi.jpg",
                            Name = "Mahi Mahi"
                        },
                        new
                        {
                            AnimalId = 15,
                            Age = 5,
                            CategoryId = 4,
                            Description = "The golden eagle is a bird of prey living in the Northern Hemisphere. It is the most widely distributed species of eagle. Like all eagles, it belongs to the family Accipitridae. They are one of the best-known birds of prey in the Northern Hemisphere",
                            ImageName = "Images\\Eagle.jpg",
                            Name = "Golden Eagle"
                        },
                        new
                        {
                            AnimalId = 16,
                            Age = 12,
                            CategoryId = 3,
                            Description = "The polar bear is a hypercarnivorous bear whose native range lies largely within the Arctic Circle, encompassing the Arctic Ocean, its surrounding seas and surrounding land masses. It is the largest extant bear species, as well as the largest extant land carnivore",
                            ImageName = "Images\\PolarBear.jpg",
                            Name = "Polar Bear"
                        },
                        new
                        {
                            AnimalId = 17,
                            Age = 4,
                            CategoryId = 3,
                            Description = "The red fox is the largest of the true foxes and one of the most widely distributed members of the order Carnivora, being present across the entire Northern Hemisphere including most of North America, Europe and Asia, plus parts of North Africa",
                            ImageName = "Images\\RedFox.jpg",
                            Name = "Red Fox"
                        },
                        new
                        {
                            AnimalId = 18,
                            Age = 6,
                            CategoryId = 2,
                            Description = "Draco is a genus of agamid lizards that are also known as flying lizards, flying dragons or gliding lizards. These lizards are capable of gliding flight via membranes that may be extended to create wings, formed by an enlarged set of ribs. They are arboreal insectivores",
                            ImageName = "\\Images\\FlyingLizard.jpg",
                            Name = "Draco - Flying Lizard"
                        },
                        new
                        {
                            AnimalId = 19,
                            Age = 6,
                            CategoryId = 4,
                            Description = "The barn owl is the most widely distributed species of owl in the world and one of the most widespread of all species of birds, being found almost everywhere except for the polar and desert regions, Asia north of the Himalayas, most of Indonesia, and some Pacific Islands",
                            ImageName = "Images\\BarnOwl.jpg",
                            Name = "Barn Owl"
                        },
                        new
                        {
                            AnimalId = 20,
                            Age = 14,
                            CategoryId = 1,
                            Description = "Swordfish, also known as broadbills in some countries, are large, highly migratory predatory fish characterized by a long, flat, pointed bill. They are a popular sport fish of the billfish category, though elusive. Swordfish are elongated, round-bodied, and lose all teeth and scales by adulthood",
                            ImageName = "Images\\SwordFish.jpg",
                            Name = "SwordFish"
                        });
                });

            modelBuilder.Entity("PetShopProject.Models.Category", b =>
                {
                    b.Property<int>("categoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("categoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("categoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            categoryId = 1,
                            Name = "Fish"
                        },
                        new
                        {
                            categoryId = 2,
                            Name = "Reptile"
                        },
                        new
                        {
                            categoryId = 3,
                            Name = "Mammal"
                        },
                        new
                        {
                            categoryId = 4,
                            Name = "Bird"
                        },
                        new
                        {
                            categoryId = 5,
                            Name = "Amphibian"
                        });
                });

            modelBuilder.Entity("PetShopProject.Models.Comment", b =>
                {
                    b.Property<int>("commentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("commentId"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("int");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("commentId");

                    b.HasIndex("AnimalId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            commentId = 1,
                            AnimalId = 1,
                            CommentText = "My favorite animal is the orca. I love to watch them play, and I love the way they move. They are very playful and they are very intelligent. This product caught my attention when I was looking for something to help capture the movement of the orca in the wild. I was surprised to find that the camera was capable of capturing the movement of an orca even when it was submerged in the water. This is a great product to capture the movement of an animal which is"
                        },
                        new
                        {
                            commentId = 2,
                            AnimalId = 1,
                            CommentText = "I've seen these little guys in the water before, but I had no idea they were so big!"
                        },
                        new
                        {
                            commentId = 3,
                            AnimalId = 1,
                            CommentText = "I own two Orca and I love them! The first time I saw one, I wanted one. I have seen video footage of other people swimming with them, and I would LOVE to be able to do this. This is a great product. "
                        },
                        new
                        {
                            commentId = 4,
                            AnimalId = 1,
                            CommentText = "Orca is a great animal to watch in the wild. They are larger than killer whales and they have a similar diet of fish. They also can be found in the wild right on the coast of the United States.\r\nI got to know Orca when I was out on a whale watching trip. I was watching a pod of orcas swimming in the Pacific Ocean off the coast of California. I was amazed by the beauty and grace of these whales. They swam and played for"
                        },
                        new
                        {
                            commentId = 5,
                            AnimalId = 1,
                            CommentText = "I've been a huge fan of Orca since I first saw it on the Discovery Channel. I love watching these guys play and interact with each other, and even once in a while they'll play with me. They're sort of like a big brother and sister who play and are just a pleasure to watch. I have a 100-gallon tank in my backyard and that's where I keep them. I just love them, and they've become my favorite kind of animal"
                        },
                        new
                        {
                            commentId = 6,
                            AnimalId = 1,
                            CommentText = "I had the opportunity to see orcas in the wild and it was truly an unforgettable experience. Their grace and intelligence was evident in the way they moved and communicated with each other"
                        },
                        new
                        {
                            commentId = 7,
                            AnimalId = 2,
                            CommentText = "I've always been fascinated by Komodo dragons and finally got to see them in person at a zoo. The enclosure was well-designed and provided a good view of the dragons, but I couldn't help feeling sad that they were in captivity"
                        },
                        new
                        {
                            commentId = 8,
                            AnimalId = 2,
                            CommentText = "I went on a guided tour to see Komodo dragons on their island and it was a unique and unforgettable experience. The guides were knowledgeable and provided a lot of information about the biology and behavior of the dragons"
                        },
                        new
                        {
                            commentId = 9,
                            AnimalId = 2,
                            CommentText = "I had the opportunity to visit a sanctuary that houses Komodo dragons and it was an amazing experience. The size and power of these animals is truly impressive and it was incredible to see them up close in their natural habitat"
                        },
                        new
                        {
                            commentId = 10,
                            AnimalId = 3,
                            CommentText = "I had the chance to visit a wildlife reserve and was lucky enough to see a herd of zebras grazing in the open field. The sight of these beautiful animals with their unique stripes was truly breathtaking"
                        },
                        new
                        {
                            commentId = 11,
                            AnimalId = 3,
                            CommentText = "I went on a safari in Africa and seeing the zebras in their natural habitat was a highlight of the trip. Their social dynamics and behavior was fascinating to observe"
                        },
                        new
                        {
                            commentId = 12,
                            AnimalId = 4,
                            CommentText = "I recently watched a documentary about great white sharks and was struck by how misunderstood these creatures are. It was eye-opening to learn about their behavior and importance in the ocean's ecosystem, and I hope more people come to appreciate and protect them"
                        },
                        new
                        {
                            commentId = 13,
                            AnimalId = 5,
                            CommentText = "I had the chance to visit a tropical bird sanctuary and was amazed by the beauty and vibrant colors of the toucans. Their big, colorful beaks and cheerful personalities were a delight to watch and the guides were very knowledgeable about these birds"
                        },
                        new
                        {
                            commentId = 14,
                            AnimalId = 5,
                            CommentText = "I went to a zoo and was impressed by the toucan exhibit. The enclosure was large and had plenty of perches and hiding spots, and the birds looked healthy and active. It was great to see these exotic birds up close and learn more about them"
                        },
                        new
                        {
                            commentId = 15,
                            AnimalId = 6,
                            CommentText = "I went to a local zoo and was disappointed in the conditions of the poison dart frog exhibit. The enclosure was too small and not well-maintained, and the frogs didn't look healthy. It's important for zoos to provide proper care for these delicate creatures"
                        },
                        new
                        {
                            commentId = 16,
                            AnimalId = 7,
                            CommentText = "I had the opportunity to visit a snake sanctuary and was amazed by the beauty and grace of the Cobra snakes. The staff was very knowledgeable and provided a lot of information about the different species and their behaviors"
                        },
                        new
                        {
                            commentId = 17,
                            AnimalId = 7,
                            CommentText = "I recently attended a snake handling demonstration and the Cobra snake was by far the most impressive. The handler was able to handle the snake with great care and expertise, and it was an educational experience to learn more about these fascinating creatures"
                        },
                        new
                        {
                            commentId = 18,
                            AnimalId = 7,
                            CommentText = "I was disappointed to see Cobra snakes being kept in small, poorly-maintained enclosures at a local zoo. It was clear that the snakes were not being provided with the proper care and space they need. It is important for zoos to provide proper care for all animals, including snakes."
                        },
                        new
                        {
                            commentId = 19,
                            AnimalId = 8,
                            CommentText = "I had the chance to go on a safari in Africa and seeing the lions in their natural habitat was a highlight of the trip. Their power and majesty was truly awe-inspiring and it was amazing to see them interact with their pride"
                        },
                        new
                        {
                            commentId = 20,
                            AnimalId = 8,
                            CommentText = "I recently visited a zoo and was impressed by the lion exhibit. The enclosure was large and provided a natural environment for the lions to roam, and the staff was knowledgeable and provided a lot of information about the animals."
                        },
                        new
                        {
                            commentId = 21,
                            AnimalId = 8,
                            CommentText = "I went to a circus and was deeply saddened by the lion act. The animals looked stressed and it was clear that they were not being treated humanely. I will not support circuses that use wild animals for entertainment"
                        },
                        new
                        {
                            commentId = 22,
                            AnimalId = 8,
                            CommentText = "I watched a documentary about lions and was struck by their intelligence and social behavior. It was eye-opening to learn about their importance to the ecosystem and the threats they face in the wild"
                        },
                        new
                        {
                            commentId = 23,
                            AnimalId = 8,
                            CommentText = "I read a book about lions and it was an excellent way to learn more about these fascinating animals. The book provides a lot of information about the biology, behavior, and conservation of lions. It was also a great way to experience the lion's life and culture from the comfort of my home"
                        },
                        new
                        {
                            commentId = 24,
                            AnimalId = 9,
                            CommentText = "I had the chance to visit a wildlife sanctuary in Australia and seeing the kangaroos in their natural habitat was a highlight of the trip. Their unique hopping gait and ability to carry their young in a pouch was truly fascinating to observe"
                        },
                        new
                        {
                            commentId = 25,
                            AnimalId = 9,
                            CommentText = "I recently visited a zoo and was impressed by the kangaroo exhibit. The enclosure was large and provided a natural environment for the kangaroos to roam, and the staff was knowledgeable and provided a lot of information about the animals"
                        },
                        new
                        {
                            commentId = 26,
                            AnimalId = 10,
                            CommentText = "I had the opportunity to go diving in a coral reef and was amazed by the beauty and vibrant colors of the lionfish. Their unique appearance and behavior made for an interesting and educational experience"
                        },
                        new
                        {
                            commentId = 27,
                            AnimalId = 11,
                            CommentText = "I had the chance to visit a lake and was amazed by the grace and beauty of the swans. Their elegant movements and the way they glide on the water was truly mesmerizing to watch"
                        },
                        new
                        {
                            commentId = 28,
                            AnimalId = 11,
                            CommentText = "I recently went to a park and saw a pair of swans building a nest. It was fascinating to watch the process and see how dedicated the pair were to each other and their offspring"
                        },
                        new
                        {
                            commentId = 29,
                            AnimalId = 11,
                            CommentText = "I was disappointed to see swans being treated poorly at a local pond. People were feeding them bread and not respecting their space, and it was clear that the swans were not being treated with the respect they deserve. It is important to remember that these are wild animals and should be treated with care and respect"
                        },
                        new
                        {
                            commentId = 30,
                            AnimalId = 12,
                            CommentText = "I recently went on a swamp tour and saw American alligators in their natural habitat. It was a truly unforgettable experience to see these powerful creatures in the wild and learn about their role in the ecosystem"
                        },
                        new
                        {
                            commentId = 31,
                            AnimalId = 12,
                            CommentText = "I was disappointed to see American alligators being kept in small, poorly-maintained enclosures at a local zoo. It was clear that the alligators were not being provided with the proper care and space they need. It is important for zoos to provide proper care for all animals, including alligators"
                        },
                        new
                        {
                            commentId = 32,
                            AnimalId = 13,
                            CommentText = "I had the opportunity to visit a nature reserve and was amazed by the vibrant colors of the fire salamanders. Their unique pattern and coloration made them easy to spot amongst the forest floor and the staff was knowledgeable and provided a lot of information about the animals and their habitat"
                        },
                        new
                        {
                            commentId = 33,
                            AnimalId = 14,
                            CommentText = "I recently caught a mahi mahi while deep sea fishing and it was an exciting and tasty experience. The fish was cooked on the boat and was some of the freshest and most flavorful fish I have ever had"
                        },
                        new
                        {
                            commentId = 34,
                            AnimalId = 14,
                            CommentText = "I recently went on a fishing trip and caught a Mahi Mahi. It was a great fight and the taste of the fresh fish was incredible. I couldn't wait to cook it for my family and friends"
                        },
                        new
                        {
                            commentId = 35,
                            AnimalId = 15,
                            CommentText = "I had the opportunity to visit a wildlife sanctuary and was amazed by the beauty and power of the golden eagle. The staff was knowledgeable and provided a lot of information about the animals, their habitat, and conservation efforts"
                        },
                        new
                        {
                            commentId = 36,
                            AnimalId = 15,
                            CommentText = "I recently went on a hike and was lucky enough to spot a golden eagle in the wild. It was an incredible experience to see such a majestic bird in its natural habitat"
                        },
                        new
                        {
                            commentId = 37,
                            AnimalId = 16,
                            CommentText = "I had the opportunity to visit a zoo and was amazed by the size and power of the polar bears. The staff was knowledgeable and provided a lot of information about the animals, their habitat, and conservation efforts"
                        },
                        new
                        {
                            commentId = 38,
                            AnimalId = 16,
                            CommentText = "I recently went on a wildlife safari and was lucky enough to spot a polar bear in the wild. It was an incredible experience to see such a majestic animal in its natural habitat"
                        },
                        new
                        {
                            commentId = 39,
                            AnimalId = 16,
                            CommentText = "I was disappointed to see polar bears being kept in small, poorly-maintained enclosures at a zoo. It was clear that the bears were not being provided with the proper care and space they need. It is important for zoos to provide proper care for all animals, including polar bears"
                        },
                        new
                        {
                            commentId = 40,
                            AnimalId = 16,
                            CommentText = "I had the opportunity to visit a polar bear exhibit at a natural history museum and was impressed by the level of detail and information provided. It was fascinating to learn about their biology, behavior, and conservation status. The exhibit was well-done and interactive which made it enjoyable for visitors of all ages"
                        },
                        new
                        {
                            commentId = 41,
                            AnimalId = 17,
                            CommentText = "I had the opportunity to visit a wildlife sanctuary and was impressed by the beauty and intelligence of the red fox. The staff was knowledgeable and provided a lot of information about the animals, their habitat, and conservation efforts"
                        },
                        new
                        {
                            commentId = 42,
                            AnimalId = 17,
                            CommentText = "I recently went on a hike and was lucky enough to spot a red fox in the wild. It was an incredible experience to see such a graceful animal in its natural habitat"
                        },
                        new
                        {
                            commentId = 43,
                            AnimalId = 17,
                            CommentText = "I had the opportunity to visit a red fox exhibit at a natural history museum and was impressed by the level of detail and information provided. It was fascinating to learn about their biology, behavior, and conservation status. The exhibit was well-done and interactive which made it enjoyable for visitors of all ages"
                        },
                        new
                        {
                            commentId = 44,
                            AnimalId = 17,
                            CommentText = "I had the chance to watch a documentary about red foxes, it was very informative and gave me a deep understanding about their behavior, diet and habitat. It was also very interesting to learn about the different subspecies of red fox and their geographic distribution"
                        },
                        new
                        {
                            commentId = 45,
                            AnimalId = 18,
                            CommentText = "I recently went on a hike in a tropical rainforest and was lucky enough to spot a Draco flying lizard in the wild. It was an incredible experience to see such a unique animal in its natural habitat"
                        },
                        new
                        {
                            commentId = 46,
                            AnimalId = 18,
                            CommentText = "I was disappointed to see Draco flying lizards being kept in small, poorly-maintained enclosures at a zoo. It was clear that the lizards were not being provided with the proper care and space they need. It is important for zoos to provide proper care for all animals, including Draco flying lizards"
                        },
                        new
                        {
                            commentId = 47,
                            AnimalId = 19,
                            CommentText = "I recently went on a hike and was lucky enough to spot a barn owl in the wild. It was an incredible experience to see such a majestic animal in its natural habitat"
                        },
                        new
                        {
                            commentId = 48,
                            AnimalId = 19,
                            CommentText = "I had the opportunity to visit a bird sanctuary and was impressed by the beauty and grace of the barn owl. The staff was knowledgeable and provided a lot of information about the animals, their habitat, and conservation efforts"
                        },
                        new
                        {
                            commentId = 49,
                            AnimalId = 20,
                            CommentText = "I went on a deep sea fishing trip and caught a swordfish. It was an exhilarating experience and the fish was delicious when we cooked it later that night"
                        },
                        new
                        {
                            commentId = 50,
                            AnimalId = 20,
                            CommentText = "I watched a documentary about swordfish and was fascinated by their strength and agility. It was also eye-opening to learn about the fishing industry and the impact on swordfish populations"
                        });
                });

            modelBuilder.Entity("PetShopProject.Models.Animal", b =>
                {
                    b.HasOne("PetShopProject.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PetShopProject.Models.Comment", b =>
                {
                    b.HasOne("PetShopProject.Models.Animal", "Animals")
                        .WithMany("Comments")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animals");
                });

            modelBuilder.Entity("PetShopProject.Models.Animal", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
